name: Mobile E2E (Android + iOS BS) + Allure Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: mobile-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    name: Android (Emulator + Appium 2 + WDIO)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache: 'npm'  # (desligado enquanto não há package-lock.json)

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install deps (no lockfile)
        run: npm install --no-audit --prefer-offline

      - name: Install Appium UiAutomator2 driver
        run: npx appium driver install uiautomator2

      - name: Run WDIO on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_6
          disable-animations: true
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect
          script: |
            npx wdio run ./wdio.conf.js

      - name: Upload allure-results (Android)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-android
          path: reports/allure-results/**
          if-no-files-found: ignore

      - name: Upload raw reports (screens, logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-android
          path: reports/**
          if-no-files-found: ignore

  ios-bs:
    name: iOS (BrowserStack)  # opcional — remova este job se não usar BS
    runs-on: ubuntu-latest
    needs: android
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BS_IOS_APP: ${{ secrets.BS_IOS_APP }} # ex.: bs://<hash>

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install --no-audit --prefer-offline

      - name: Run WDIO on BrowserStack iOS
        run: npx wdio run ./wdio.bs.ios.conf.js

      - name: Upload allure-results (iOS)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-ios
          path: reports/allure-results/**
          if-no-files-found: ignore

  build-allure:
    name: Build Allure (merge Android + iOS)
    runs-on: ubuntu-latest
    needs: [android, ios-bs]   # se não usar iOS, troque para: needs: android
    if: always()

    steps:
      - name: Download allure-results Android
        uses: actions/download-artifact@v4
        with:
          name: allure-results-android
          path: ./allure-results/android
        continue-on-error: true

      - name: Download allure-results iOS (se existir)
        uses: actions/download-artifact@v4
        with:
          name: allure-results-ios
          path: ./allure-results/ios
        continue-on-error: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Merge results e gerar Allure
        run: |
          mkdir -p merged-results
          [ -d "allure-results/android" ] && cp -r allure-results/android/* merged-results/ || true
          [ -d "allure-results/ios" ] && cp -r allure-results/ios/* merged-results/ || true
          if [ -d "merged-results" ] && [ "$(ls -A merged-results 2>/dev/null)" ]; then
            npx --yes allure-commandline generate merged-results --clean -o allure-report
          else
            mkdir -p allure-report
            cat > allure-report/index.html <<'HTML'
            <html><body><h2>Sem resultados do Allure</h2>
            <p>O job anterior não gerou <code>allure-results</code>. Verifique os logs do job Android.</p>
            </body></html>
            HTML
          fi

      - name: Upload Pages artifact (Allure)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

  deploy-pages:
    name: Deploy Allure to GitHub Pages
    needs: build-allure
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
